name: Repo Patch Apply

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: Commit message
        required: true
      frontend_b64:
        description: Base64 for app/src/frontend/index.jsx (optional)
        required: false
      backend_b64:
        description: Base64 for app/src/backend/index.js (optional)
        required: false
      package_b64:
        description: Base64 for app/package.json (optional)
        required: false
      manifest_b64:
        description: Base64 for app/manifest.yml (optional)
        required: false

permissions:
  contents: write

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Apply patches
        shell: bash
        run: |
          set -euo pipefail
          changed=0
          write_if() {
            local val="$1"
            local path="$2"
            if [ -n "$val" ]; then
              mkdir -p "$(dirname "$path")"
              echo "$val" | base64 -d > "$path"
              echo "Wrote $path"
              changed=1
            fi
          }
          write_if "${{ github.event.inputs.frontend_b64 }}" "app/src/frontend/index.jsx"
          write_if "${{ github.event.inputs.backend_b64 }}"  "app/src/backend/index.js"
          write_if "${{ github.event.inputs.package_b64 }}"  "app/package.json"
          write_if "${{ github.event.inputs.manifest_b64 }}" "app/manifest.yml"
          if [ "$changed" -eq 0 ]; then
            echo "No inputs provided"; exit 1
          fi

      - name: Commit
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "${{ github.event.inputs.commit_message }}"
          git push
