name: Forge CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: forge-cicd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-install:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      # Forge CLI reads these automatically; do not run `forge login` in CI
      FORGE_EMAIL: ${{ secrets.FORGE_EMAIL }}          # ahmed.m.m.abdellatif@hotmail.com
      FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}  # your new token (secret)
      ATLASSIAN_SITE: ${{ secrets.ATLASSIAN_SITE }}    # jiraagentmode.atlassian.net

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Forge CLI
        run: npm install -g @forge/cli

      - name: Disable Forge CLI analytics (required for non-TTY CI)
        run: forge settings set usage-analytics false

      - name: Install dependencies (app)
        working-directory: app
        run: |
          if [ -f package-lock.json ]; then npm ci; elif [ -f package.json ]; then npm i; else echo "No package.json found in /app yet"; fi

      - name: Lint (non-blocking)
        working-directory: app
        run: forge lint || echo "lint warnings, continuing"

      - name: Deploy to development
        working-directory: app
        run: forge deploy --environment development

      - name: Install on Confluence (development)
        working-directory: app
        run: |
          forge install \
            --product confluence \
            --site "$ATLASSIAN_SITE" \
            --environment development \
            --confirm-scopes \
            --non-interactive
