name: Forge CI/CD (self-healing)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: forge-cicd-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write   # needed for the self-heal commit

jobs:
  deploy-install:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    env:
      FORGE_EMAIL: ${{ secrets.FORGE_EMAIL }}
      FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
      ATLASSIAN_SITE: ${{ secrets.ATLASSIAN_SITE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Forge CLI
        run: npm install -g @forge/cli@latest

      - name: Disable Forge CLI analytics (avoid non-TTY prompts)
        run: forge settings set usage-analytics false

      # Keep this to auto-fix missing app.id/runtime and commit back
      - name: Ensure app.id and runtime in manifest (self-heal)
        working-directory: app
        shell: bash
        run: |
          set -euo pipefail
          test -f manifest.yml

          echo "== Before =="
          sed -n '1,200p' manifest.yml || true

          if ! grep -qE '^\s*id:\s*ari:cloud:ecosystem::app/' manifest.yml; then
            echo "No app.id -> registering app name 'Jira Agent Mode'..."
            forge register "Jira Agent Mode"
          fi

          if ! grep -qE '^\s*runtime:' manifest.yml; then
            awk '
              BEGIN{added=0}
              { print }
              END{
                if (!added) {
                  print ""
                  print "app:"
                  print "  runtime:"
                  print "    name: nodejs20.x"
                }
              }
            ' manifest.yml > manifest.tmp && mv manifest.tmp manifest.yml
          fi

          # Drop deprecated app.name if present
          perl -0777 -pe 's/\napp:\n(\s*name:.*\n)/\napp:\n/s' -i manifest.yml || true

          echo "== After =="
          sed -n '1,220p' manifest.yml || true

          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add manifest.yml
            git commit -m "ci: ensure Forge app.id and runtime"
            git push
          fi

      - name: Install dependencies (app)
        working-directory: app
        run: |
          if [ -f package-lock.json ]; then npm ci;
          elif [ -f package.json ]; then npm i;
          else echo "No package.json in /app"; fi

      - name: Lint (non-blocking)
        working-directory: app
        run: forge lint || echo "lint warnings, continuing"

      - name: Deploy to development
        working-directory: app
        run: forge deploy --environment development

      # REQUIRED: install/upgrade on Confluence
      - name: Install on Confluence (development)
        working-directory: app
        run: |
          forge install \
            --product confluence \
            --site "$ATLASSIAN_SITE" \
            --environment development \
            --upgrade \
            --confirm-scopes \
            --non-interactive

      # REQUIRED: install/upgrade on Jira (for Jira scopes)
      - name: Install on Jira (development)
        working-directory: app
        run: |
          forge install \
            --product jira \
            --site "$ATLASSIAN_SITE" \
            --environment development \
            --upgrade \
            --confirm-scopes \
            --non-interactive
