name: Forge CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: forge-cicd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-install:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    env:
      FORGE_EMAIL: ${{ secrets.FORGE_EMAIL }}
      FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
      ATLASSIAN_SITE: ${{ secrets.ATLASSIAN_SITE }}
      SITE_URL: https://${{ secrets.ATLASSIAN_SITE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Forge CLI
        run: npm install -g @forge/cli@latest

      - name: Disable Forge CLI analytics (avoid non-TTY prompts)
        run: forge settings set usage-analytics false

      - name: Install dependencies (app)
        working-directory: app
        run: |
          if [ -f package-lock.json ]; then npm ci;
          elif [ -f package.json ]; then npm i;
          else echo "No package.json in /app"; fi

      - name: Lint (non-blocking)
        working-directory: app
        run: forge lint || echo "lint warnings, continuing"

      - name: Deploy to development
        working-directory: app
        run: forge deploy --environment development

      # Confluence install (plain, then upgrade if already installed)
      - name: Install on Confluence (development)
        working-directory: app
        shell: bash
        run: |
          set -e
          forge install \
            --product Confluence \
            --site "$SITE_URL" \
            --environment development \
            --confirm-scopes \
            --non-interactive \
          || forge install \
            --product Confluence \
            --site "$SITE_URL" \
            --environment development \
            --upgrade \
            --confirm-scopes \
            --non-interactive

      # Jira install (required because we request Jira scopes)
      - name: Install on Jira (development)
        working-directory: app
        shell: bash
        run: |
          set -e
          forge install \
            --product Jira \
            --site "$SITE_URL" \
            --environment development \
            --confirm-scopes \
            --non-interactive \
          || forge install \
            --product Jira \
            --site "$SITE_URL" \
            --environment development \
            --upgrade \
            --confirm-scopes \
            --non-interactive
